### ISSUE TITLE
We need git rule.

### ISSUE THREAD

**Issue by akifo** [chadananda/ilm-client#2]
Let's discuss
I recommend that..

| branch | for what |
| ------------- | ------------- |
| master | for release as a product. |
| dev | Development branch. Once the code is stable and ready to release, merge it into master. Before the release, this branch will be the latest version. |
| issue-12 | for implement Task. Branch from dev and merge with dev. |
| feature-something | for add some feature. |

**Comment by dnotes** [comment]
I would like this as well.

With our current ticketing strategy, I don't know if there will be much
difference between issue- and feature- branches; and if they are basically
the same perhaps we could just use issue- for simplicity.

I would also add space for hotfix- branches from gitflow conventions,
branched from master and merged to both master (with immediate minor
versioning) and dev.
