### ISSUE TITLE
Todo and Check list for akifo

### ISSUE THREAD

**Issue by akifo** [chadananda/ilm-client#22]
This is check list just for me.

## When developing with docker ...
- http://localhost:3000/
- checked `admin` `Librarian`

**Comment by akifo** [comment]
## You can't use method at vuex state

`/mixins/access.js`
```
this.$store.state.auth.confirmRole('admin')
```

**Comment by chadananda** [comment]
Not sure the best way to share a global authentication object like this.

**Comment by akifo** [comment]
I'm not familiar with pouchDB.

If written here, meta-data-editing is completed to a certain extent.
https://github.com/chadananda/ilm-client/blob/feature-implement-meta-data-editing/src/store/index.js#L160-L172

**Comment by akifo** [comment]
It's done.
