### ISSUE TITLE
Client: Book cover editor

### ISSUE THREAD

**Issue by akifo** [chadananda/ilm-client#3]
- [x] To be able to move the position of the text
- [x] Make bookcover selectable
- [ ] Enable to add bookcover
- [ ] Processing when pressing Save button
- [ ] About initial display when modal

**Comment by akifo** [comment]
## About initial display when modal

Information required for props
- selected bookcover ID 
- title
  - text
  - top
  - left
- author
  - text
  - top
  - left

**Comment by akifo** [comment]
## Enable to add bookcover
Which?
- Send an image to the server with the API and then display the image from server
- display the image on the client side

**Comment by chadananda** [comment]
How would the generation of the final image work? Do we superimpose the text on the original (large) image at a scaled size and output a bitmap (as png)?  Would CSS rules be applicable? If so, we need to mess around with shadows and emboss to get something that looks more like the sample image.

**Comment by akifo** [comment]
I think that it is good to manage image information with book cover, text, CSS. so, We can applicable CSS rules probably.

It is still under consideration, but it is like this.

```
{
  "book_cover_id": 11,
  "title": {
    "text": "aaaaaaa",
    "styles": {
      "top": 0,
      "left": 0,
      "font-size": "12px",
      "text-shadow": "1px 1px 1px #000"
    },
  "author": {
    "text": "bbbbbbbb",
    "styles": {
      "top": 0,
      "left": 0,
      "font-size": "12px",
      "text-shadow": "1px 1px 1px #000"
    }
  }
}
```

**Comment by chadananda** [comment]
But how do we generate an output PNG from this? Canvas wizardry?

**Comment by akifo** [comment]
I do not know how to generate PNG from these data (Image Object Data) now.

So, if we pass props to (Image Object Data), we will make a separate component that can display bookcover in various sizes.

If there is a way to generate PNG, I would like to do though, but I don't know how.
