### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by akifo** [chadananda/ilm-client#7]
We should keep the eslint rules.

**Comment by chadananda** [comment]
If you can figure out how to just remove the rule prohibiting trailing whitespace, then eslint can remain.  ;)

**Comment by akifo** [comment]
I am using sublime text.
With preference settings, trailing whitespace can be automatically deleted simply by setting as follows.

```
"trim_trailing_white_space_on_save": true
```

**Comment by chadananda** [comment]
I cannot have this rule turned on in Sublime because I am constantly using it for editing text files which are destroyed if EOL whitespace is removed.

This is one of those dumb rules that has no value anyway. I just could not figure out how to turn off this rule in esLint.

**Comment by akifo** [comment]
You can customize Sublime Text as you want.

In case of my Mac...
`/Users/akiho/Library/Application Support/Sublime Text 3/Packages/User/Markdown.sublime-settings`
```
// These settings override both User and Default settings for the Markdown syntax
{
    // Which file extensions go with this file type?
    "extensions":
    [
        "md",
        "mdown",
        "mdwn",
        "mmd",
        "txt"
    ],

    // Set to true to removing trailing white space on save
    "trim_trailing_white_space_on_save": false
}
```

or Although no error occurs even with current eslint setting.

```
"no-trailing-spaces": 0,
```

So, I think that eslint's rule can be used as it is.

**Comment by chadananda** [comment]
eslint is supposed to be configurable, and this is a nonsense rule. The solution should be to disable the bad rule on the webpack side.
